### ISSUE TITLE
Eclipse incompatibility?

### ISSUE THREAD

**Issue by pranaygp** [Togira/CS125-Research#9]
There are a few issues that I have every time I open up work done by anyone else. 

The IDE throws a whole bunch of errors.

1 that's common is that it doesn't recognize the package `Java.util`. It has to be `java.util`. Basically, always a lowercase j.

when constructor calls another version of the constructor (example: the call to the `Student(code)` constructor from `Student(code, record)`.

I had to switch it to `this(code)` to suppress IDE errors.

Does anyone know why this happens?

**Comment by NavneethJayendran** [comment]
I guess it's just a syntactic rule in Java that calling another constructor requires use of "this" instead of the class name. 
http://stackoverflow.com/questions/285177/how-do-i-call-one-constructor-from-another-in-java
Sorry, I've tried my best to avoid errors but I've kind of been doing this without an IDE (Eclipse isn't working for me right now). In this future I'll make sure to try compiling before making changes.

**Comment by pranaygp** [comment]
@NavneethJayendran That makes sense.

I was assuming this had to do with different versions of JDK/Eclipse

This makes things easier.

Closing Issues.
